// <auto-generated />
namespace Shop.Infrastructure.EFDataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nombreminuscula : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nombreminuscula));
        
        string IMigrationMetadata.Id
        {
            get { return "201908291653454_nombre minuscula"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
